name: PDF to CSV Converter

on:
  push:
    paths:
      - 'pdf-folder/*.pdf'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyPDF2

      - name: Identify the uploaded PDF file
        id: identify_pdf
        run: |
          echo "Identifying uploaded PDF file"
          pdf_file=$(git diff --name-only HEAD^ HEAD | grep '^pdf-folder/.*\.pdf$' | head -n 1)
          if [ -z "$pdf_file" ]; then
            echo "No new PDF file found in the latest commit."
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "PDF file identified: $pdf_file"
            echo "pdf_path=$pdf_file" >> $GITHUB_OUTPUT
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Run PDF to CSV Script
        if: steps.identify_pdf.outputs.skip != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Running PDF to CSV conversion script"
          python pdf_to_csv.py "${{ steps.identify_pdf.outputs.pdf_path }}" "${{ github.repository }}" "${{ github.ref_name }}" "$GITHUB_TOKEN"

      - name: Log workflow completion
        if: always()
        run: |
          echo "Workflow completed. Check logs for any errors or issues."
