name: PDF to CSV Converter

on:
  push:
    paths:
      - 'pdf-folder/*.pdf'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyPDF2

      - name: Identify the uploaded PDF file
        id: identify_pdf
        run: |
          echo "Identifying uploaded PDF file"
          echo "::set-output name=pdf_path::$(git diff --name-only HEAD^ HEAD | grep 'pdf-folder/.*\.pdf')"

      - name: Run PDF to CSV Script
        run: |
          echo "Running PDF to CSV conversion script"
          python pdf_to_csv.py "${{ steps.identify_pdf.outputs.pdf_path }}" "RodrigoGF-Niko/cfe-receipt_pdf-to-csv" "main" "${{ secrets.GITHUB_TOKEN }}"
