name: PDF to CSV Converter

on:
  push:
    paths:
      - 'pdf-folder/*.pdf'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyPDF2

      - name: Identify the uploaded PDF file
        id: identify_pdf
        run: |
          echo "Identifying uploaded PDF file"
          pdf_file=$(git diff --name-only HEAD^ HEAD | grep 'pdf-folder/.*\.pdf')
          if [ -z "$pdf_file" ]; then
            echo "Error: No PDF file found in the latest commit."
            exit 1
          fi
          echo "PDF file identified: $pdf_file"
          echo "::set-output name=pdf_path::$pdf_file"

      - name: Log PDF path
        run: |
          echo "PDF path: ${{ steps.identify_pdf.outputs.pdf_path }}"

      - name: Wait for file to be fully uploaded
        run: |
          echo "Waiting for the file to be fully uploaded"
          sleep 10  # Wait for 10 seconds to ensure the file is fully uploaded

      - name: Run PDF to CSV Script
        run: |
          echo "Running PDF to CSV conversion script"
          python pdf_to_csv.py "${{ steps.identify_pdf.outputs.pdf_path }}" "RodrigoGF-Niko/cfe-receipt_pdf-to-csv" "main" "${{ secrets.GITHUB_TOKEN }}"
